name: Django apps

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        include:
          - django-version: [2.2, 3.0.0, 3.1]
          - django-app: [halo, splitviewsmodels, profilpenggunafoto]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        django-version: ${{ matrix.django-version }}
        django-app: ${{ matrix.django-app }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django~=${{ matrix.django-version }}
        pip install coverage
    - name: Install dependencies for Django App with ImageField
      if: matrix.django-app == 'profilpenggunafoto'
      run: |
        pip install Pillow        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Setup Django Project
      run: |
        django-admin startproject jagodjango .
        python manage.py migrate
    - name: Setup Django Apps and Tests
      run: |
        echo ${{ matrix.django-app }}
        python manage.py makemigrations --settings=${{ matrix.django-app }}.settings_tests ${{ matrix.django-app }}
        python manage.py migrate --settings=${{ matrix.django-app }}.settings_tests ${{ matrix.django-app }}
        python manage.py test --settings=${{ matrix.django-app }}.settings_tests ${{ matrix.django-app }}
    - name: Test Coverage and Generate Report
      run: |
        echo ${{ matrix.django-app }}
        coverage run --source=${{ matrix.django-app }} manage.py test --settings=${{ matrix.django-app }}.settings_tests ${{ matrix.django-app }}
        coverage xml --omit=${{ matrix.django-app }}/admin.py,${{ matrix.django-app }}/*tests.py,${{ matrix.django-app }}/migrations/*.py
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        name: ${{ matrix.python-version }}/${{ matrix.django-version }}/${{ matrix.django-app }}
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: ./coverage.xml
